###
GET http://localhost:5001/


###
POST http://localhost:5001/auth/register
Content-Type: application/json

{
    "username":"harsh@singh",
    "password":"123121"
}

###
POST http://localhost:5001/auth/login
Content-Type: application/json

{
    "username":"harsh@singh",
    "password":"123121"
}

###
GET http://localhost:5001/todos/
Authorization: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM1MzkwMjA5LCJleHAiOjE3MzU0NzY2MDl9.l34tMGpRWyG1wLjfXVFWFEivyMIJ-uYiFdTnUFDwaSY'


###
POST http://localhost:5001/todos/
Authorization: 
Content-Type: application/json

{
    "task":"Meow Meow Cat :)"
}


###
PUT http://localhost:5001/todos/2
Authorization: 
Content-Type: application/json

{
    "completed":1
}

###
DELETE http://localhost:5001/todos/2
Authorization: 